name: Android CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Gradle (for wrapper generation)
        run: |
          sudo apt-get update
          sudo apt-get install -y gradle

      - name: Verify Gradle
        run: gradle -v

      - name: Generate Gradle Wrapper if missing
        run: |
          if [ ! -f gradle/wrapper/gradle-wrapper.jar ]; then
            gradle wrapper --gradle-version 9.1
          else
            echo "Gradle wrapper already exists, skipping generation."
          fi

      - name: Setup Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Build Debug
        run: |
          ./gradlew assembleDebug

      - name: Run Unit Tests
        run: |
          ./gradlew testDebugUnitTest

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk
